// <auto-generated />
using Lab_CoffeeShop_EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab_CoffeeShop_EFCore.Migrations
{
    [DbContext(typeof(CoffeeShopContext))]
    [Migration("20190731190249_InitialCoffeeShopMigration")]
    partial class InitialCoffeeShopMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab_CoffeeShop_EFCore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Some damn fine coffee",
                            Name = "Black Coffee",
                            Price = 2,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Takes forever",
                            Name = "Pour Over",
                            Price = 4,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Frozen, chewable",
                            Name = "Iced Coffee",
                            Price = 3,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Smaller cup, larger price",
                            Name = "Espresso",
                            Price = 4,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Lab_CoffeeShop_EFCore.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
